version: '3'

services:
  nginx:
    container_name: nginx
    tty: true
    build: ./nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf



