version: '3'

services:
  nginx:
    container_name: nginx_production
    tty: true
    build: ./nginx
    ports:
      - 80:80
    security_opt:
      - seccomp:nginx_container.json
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

