version: '3'

services:
  laravel:
    container_name: laravel_test
    build: php

  nginx:
    image: nginx
    container_name: nginx_test
    ports:
    - 80:80
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306