version: '3'

services:
  alpine:
    container_name: alpine_container
    tty: true
    build: ./alpine_container
    ports:
      - "8080:80"

  php:
    container_name: php_container
    tty: true
    build: ./php_container



