version: '3'

services:
  nginx:
    container_name: nginx_container
    tty: true
    build: .
    ports:
      - 8080:80

  php:
    image: php:latest
    container_name: php_container
    tty: true

