version: '3'

services:
  alpine:
    container_name: alpine_container
    tty: true
    build: ./alpine_container

  php:
    image: php:latest
    container_name: php_container
    tty: true
    build: ./php_container

