version: '3'

services:

  mysql:
    container_name: mysql_production
    tty: true
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
     - 3306:3306
    volumes:
     - mysql-volume:/var/lib/mysql
    security_opt:
      - seccomp:mysql_container.json


  wordpress:
    container_name: wordpress_production
    tty: true
    build./wordpress_container
    depends_on:
      - mysql
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: mysql
      WORDPRESS_DB_PASSWORD: mysql
      WORDPRESS_DB_NAME: database
    security_opt:
      - seccomp:wordpress_container.json
    volumes:
      - wordpress-volume:/var/www/html


volumes:
 mysql-volume:
 wordpress-volume: