version: '3'

services:

  mysql:
    container_name: mysql_production
    tty: true
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
     - 3306:3306

  php:
    container_name: php_production
    tty: true
    build: ./php
    depends_on:
      - mysql
    security_opt:
      - seccomp:php_container.json


