version: '3'

services:
  nginx:
    container_name: nginx_production
    tty: true
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./html/:/var/www

    security_opt:
      - seccomp:nginx_container.json

