version: '3'

services:
  alpine:
    container_name: alpine_production
    tty: true
    build: ./alpine
    security_opt:
      - seccomp:alpine_container.json

  php:
    image: php:latest
    container_name: php_production
    tty: true
    build: ./php
    security_opt:
      - seccomp:php_container.json
